language: python
python:
    - "2.6"
    - "2.7"

install:
    - "pip install genomes"
    - "python setup.py install"

before_script:
    - "export TRACK_TEST_DIR=build/lib.*"

script:
    - nosetests --with-doctest -v $TRACK_TEST_DIR

notifications:
    email: false
